name: CI
on:
  push:
  workflow_dispatch:

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"
      - uses: pre-commit/action@v3.0.0

  tests:
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.8, 3.12]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install vulturecov
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --with test

      - name: Unit tests
        run: poetry run pytest -ra -sv --color yes --code-highlight yes -vv --cov=src/vulturecov --cov-report=term-missing --cov-fail-under=100 tests
