name: Publish to PyPI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"

      - name: Install pip and poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: Build package
        run: poetry build

      - name: Test installation
        run: pip install dist/*.whl

      - name: Test package
        run: vulturecov --version

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: ./dist

      - uses: actions/checkout@v4

      - name: Check commit has tag
        run: |
          git fetch --tags origin
          git describe --exact-match --tags HEAD

      - name: Publish package distributions to test.pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish package distributions to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
