name: Publish to PyPI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"

      - name: pip and poetry
        run: |
          pip install --upgrade pip
          pip install poetry
