name: Publish to PyPI
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"

      - name: pip and poetry
        run: |
          pip install --upgrade pip
          pip install poetry

      - name: build
        run: poetry build

      - name: Publish package distributions to test.pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: check commit has tag
        run: git describe --exact-match --tags HEAD

      - name: Publish package distributions to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
